import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import Aside from "@/components/Aside";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "XDMunity",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-neutral-800 text-slate-50 ${inter.className}`}>
        <AuthProvider>
          <div className="grid grid-cols-[270px_minmax(900px,_1fr)]">
            <Aside />
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
